source "https://rubygems.org"

gem "fluentd", "1.2.2"
gem "oj", "3.5.1"
gem "fluent-plugin-concat"
gem "fluent-plugin-logzio"
gem "fluent-plugin-record-modifier"
gem "fluent-plugin-detect-exceptions"
gem "fluent-plugin-kubernetes_metadata_filter"
gem "fluent-plugin-systemd"
